// USERS
INSERT INTO USERS (LOGIN, NAME, EMAIL, BIRTHDAY) VALUES ('u1','u1','u1@ya.ru', CURRENT_DATE);
INSERT INTO USERS (LOGIN, NAME, EMAIL, BIRTHDAY) VALUES ('u2','u2','u2@ya.ru', CURRENT_DATE);
INSERT INTO USERS (LOGIN, NAME, EMAIL, BIRTHDAY) VALUES ('u3','u3','u3@ya.ru', CURRENT_DATE);
//FILMS
INSERT INTO FILMS (NAME, DESCRIPTION, DURATION, RELEASE_DATE, MPA_ID) VALUES ('f1', 'f1', 100, CURRENT_DATE, 1);
INSERT INTO FILMS (NAME, DESCRIPTION, DURATION, RELEASE_DATE, MPA_ID) VALUES ('f2', 'f2', 100, CURRENT_DATE, 2);
INSERT INTO FILMS (NAME, DESCRIPTION, DURATION, RELEASE_DATE, MPA_ID) VALUES ('f3', 'f3', 100, CURRENT_DATE, 3);